### ISSUE TITLE
Used for writing?

### ISSUE THREAD

**Issue by keesj** [newaetech/CANoodler#2]
Hello

I would like to use the Canoodler to write to the can bus. 

From reading the data sheet of the sn65hvd252 I would need to set pin 8 (S) 
to high to enable the TX out but I do not see this pin exposed anywhere on the bus.

am I missing something?
http://www.ti.com/lit/ds/symlink/sn65hvd252.pdf

**Comment by colinoflynn** [comment]
The P/N is SN65HVD232D - that has pin 8 as a N/C.

**Comment by keesj** [comment]
I see thank you! 
![selection_066](https://user-images.githubusercontent.com/57112/39152280-1ee521d4-4748-11e8-89eb-1f9e4c71aef2.png)
